[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
payment_page_stamps = "4jVkFiF35erAvhSUCKWqt7VpLZD7LdqGMJyMkkHvhyP2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mehulsrivastava/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
