[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stamps = "BG5jXZkjdu5zJjDZvncLBRi1LNBVo23Q8W1uxBCiMAn9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mehulsrivastava/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
