[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pages = "Due8TAGvBMeKWY8XaFXVnLgQZj5FdVbKUVUrWDyQU2ye"
stamps = "Bq879qyHmwZ7GWmz1FZBaKqwvH6iiSpzAJjYZuKFYKuz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mehulsrivastava/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
