[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
points_page = "7ibPg4fmTEjLufBX4vFUK2ZsG9emD5bGLqnZmfFayKGx"
stamps_page = "CpPqrUDwBuh7HJCPfqMEg9VeVnnuiqvQnsGfZSbuc48y"
stamps_history = "47RVTDVSkuTeiqPHEEWWnMxQwQpEefNNJA8ztPbwcvTQ"

[programs.devnet]
points_page = "7ibPg4fmTEjLufBX4vFUK2ZsG9emD5bGLqnZmfFayKGx"
stamps_page = "CpPqrUDwBuh7HJCPfqMEg9VeVnnuiqvQnsGfZSbuc48y"
stamps_history = "47RVTDVSkuTeiqPHEEWWnMxQwQpEefNNJA8ztPbwcvTQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mehulsrivastava/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
